### ISSUE TITLE
chore: Fix layout with cards on home page

### ISSUE THREAD

**Issue by GetBlackBoxSolutions** [dallassoftwaredevelopers/DSDsite#108]
## Task
![image](https://github.com/user-attachments/assets/530dbb01-e651-489d-aacf-65a5517f452f)

Fix the cards on the home page so that they align together.
Adjust the cards so that they shrink until they get into mobile view at which point they will turn into one column. 

[details of issue]

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by climaxmba** [comment]
Hello @GetBlackBoxSolutions, how about a `WEB-59` label for this issue?

**Comment by SamuelHe2024** [comment]
Claiming this chore
