### ISSUE TITLE
chore: Links with SVG icons only need to have accessable text

### ISSUE THREAD

**Issue by dan-mba** [dallassoftwaredevelopers/DSDsite#114]
**Describe the bug**
Any link needs text that can be accessed by a screen reader.
Most of the links on the site that use an SVG icon (socials, etc) do not.
[SocialLinks.tsx](https://github.com/dallassoftwaredevelopers/DSDsite/blob/main/src/app/components/socialSection/socialLinks.tsx)

Options to fix this:
Add [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) to the link
Add [sr-only](https://tailwindcss.com/docs/screen-readers) span within the link (link to tailwind implementation of sr-only)

**Comment by PratikThoratNortheastern** [comment]
Hey, Can I work on this? I created a fork and I am in the process of understanding the code base, May be this issue can help me contribute.

**Comment by GetBlackBoxSolutions** [comment]
@PratikThoratNortheastern , are you still interested in working on this project?

**Comment by PratikThoratNortheastern** [comment]
@GetBlackBoxSolutions Yes. I have been away for quite a while but now that I am back I want to get up and running

**Comment by GetBlackBoxSolutions** [comment]
> @GetBlackBoxSolutions Yes. I have been away for quite a while but now that I am back I want to get up and running. Please let me know if there is anything you need from me before I start?

@PratikThoratNortheastern everything should be in the description and you can get started as soon as you can. Let me know if you have any questions.

**Comment by dgarcia-appdev** [comment]
This ticket is up for grabs

**Comment by pavittarx** [comment]
@dgarcia-appdev Can you assign this to me? 

Also a few clarifying questions: 
1. After inspecting through the website, I did not see any aria-labels applied. Does it need to be just for the svgs as the issue suggests, or for all the links in the website?
2. Do you have any suggestions on how they should be labelled or I can add descriptive text and we could work this out in the PR?

**Comment by dgarcia-appdev** [comment]
@pavittarx add an area-label to the svgs with the name of the it (i.e. Meetups.com, Discord, LinkedIn)
