### ISSUE TITLE
chore: fix typo on about page

### ISSUE THREAD

**Issue by raygdev** [dallassoftwaredevelopers/DSDsite#116]
Found a typo on the about page. `Explore what Dallas Software Developers as to offer` which I assume was meant to be `has` instead of `as`. If you'd allow it I can make a quick commit for the fix and open a PR for this issue. Chore seemed to be the most appropriate template since there wasn't another one that seemed to fit.

**Comment by KrownWealth** [comment]
Hi @raygdev,
I would love to work on this chore. 
![Dallas-Software-Developers-11-04-2024_04_36_AM](https://github.com/user-attachments/assets/a755602e-34f3-40ac-be14-86dbfce8462f)

**Comment by raygdev** [comment]
@KrownWealth I'm not a maintainer on this project so I don'treally have any permissions to give. I just wanted to contribute and opened the issue to potentially make a PR. You are more than welcome to it if you'd like. [Here](https://github.com/dallassoftwaredevelopers/DSDsite/blob/main/src/app/about/page.tsx#L23) is the file it's in.

**Comment by KrownWealth** [comment]
Thank you for the highlight. I would wait for the project maintainer approval.

**Comment by casacava** [comment]
@KrownWealth Hey there, did you already start this? I didn't see a branch created yet for this issue and I could definitely take it if you haven't already.

**Comment by GetBlackBoxSolutions** [comment]
@KrownWealth sorry for the delay. Will you be able to take this?

**Comment by KrownWealth** [comment]
Thanks for your response. I will it it.

**Comment by KrownWealth** [comment]
I have created a Pull Request for this issue.
