### ISSUE TITLE
chore: Edit right side of footer

### ISSUE THREAD

**Issue by casacava** [dallassoftwaredevelopers/DSDsite#117]
The Figma file has the bottom right side of the footer listing 4 links: Home, Events and Meetups, The Community, and Get Involved. Currently the app is displaying just 3 links with different titles. This issue is just to rename existing links/add in the home link in the footer. Attached is screenshot from dev.

<img width="525" alt="Screenshot 2024-11-15 at 11 05 47 AM" src="https://github.com/user-attachments/assets/3a414bcb-63f3-40ff-bba5-196ca24cd9d2">

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by amelia2802** [comment]
Hi @dgarcia-appdev , could you please assign it to me?

**Comment by amelia2802** [comment]
@dgarcia-appdev , I have closed the old pull request and created a new one.
