### ISSUE TITLE
chore: Responsive Card Section button on cards (WEB-15)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#25]
## Task

This task is to add a button onto the cards like so:
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/60358e48-b9f6-40d7-a820-b0af6bd4cba5)

The button styles:
Color 3C3DB9
width 200px
height 45 px
border radius of 15.
font size of 18 with a font weight of 900.

button text should say
Go To A Meetup 
Community Impact
Join Our Cohort

Each button will need a redirect.
The first redirect will take them to our meetup page, this should open in a new tab leaving the existing tab there.
https://www.meetup.com/dallas-software-developers-meetup/

The other two will not 
send them anywhere yet as those pages have not been built. They will be pages on this website.
Reference the figma file in the readme if you need any additional help.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by joshuaow91** [comment]
#27
