### ISSUE TITLE
bug: Logo on Mobile version showing broken image

### ISSUE THREAD

**Issue by joshuaow91** [dallassoftwaredevelopers/DSDsite#28]
" ⨯ The requested resource isn't a valid image for /public/assets/dsd-circle-logo.png received text/html; charset=utf-8"

<img width="631" alt="Screenshot 2024-03-07 at 3 31 29 PM" src="https://github.com/dallassoftwaredevelopers/DSDsite/assets/113389785/484db491-eb56-4cd5-a17c-8f2565baaae1">

**Comment by TheDThompsonDev** [comment]
Great find!

**Comment by joshuaow91** [comment]
> Great find!

Also mobile nav menu not showing, was t sure if that was just on my end though
