### ISSUE TITLE
bug: Font weight of card text is incorrect

### ISSUE THREAD

**Issue by coffee2theorems** [dallassoftwaredevelopers/DSDsite#30]
**Describe the bug**
On the home page the font weight does not match the figma design. 

**To Reproduce**
1. Build project
2. Run Website
3. Visit homepage and observe the font weight
4. Compare to figma design

**Expected behavior**
The font weight is defaulting to bold where it needs to be light.

**Screenshots**
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/7843313/12a2f06e-7ada-4ec6-962d-490b99b87c09)

**Desktop (please complete the following information):**

- OS: Mac OSX 14.4
- Browser Firefox
- Version 123.0.1

**Comment by TheDThompsonDev** [comment]
Adjusted the import font and merged. This is resolved now.
