### ISSUE TITLE
chore: fix prettier file (WEB-16)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#33]
## Task

Task is being handled by Braydon Coyer. We had a discussion around this issue and he is currently working on it.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by braydoncoyer** [comment]
Picking up 💪
