### ISSUE TITLE
chore: Banner Height Adjustment (WEB-18)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#36]
## Task

The height of the banner should be at least 350px.
This is how it should look
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/fae90f69-91b2-4748-bdae-74eadb4d999e)

This is how it currently looks
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/ec1a1ff4-c942-4867-b8d7-200d336c4f8d)

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by NoelCov** [comment]
Hi, I'd like to work on this!
