### ISSUE TITLE
fix: in the navbar the font weight is off. (WEB-19)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#38]
In the top Navbar the font-weights have been taken off. Needs to be fixed with a font-weight of 900. If working on this ticket comment below.
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/bc934de7-d517-49d5-89cd-f6155554fbb2)

**Comment by sprashanthv-dev** [comment]
Hi, I would like to work on this!
