### ISSUE TITLE
fix: Button text has underlines on it (WEB-20)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#39]
Each button has a faint underline on the text. This needs to be removed. 
If working on this ticket comment below.
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/048fdc7b-620e-4cd6-a156-d863d08b0c0c)

**Comment by UsmanCanCode** [comment]
I can take it
