### ISSUE TITLE
chore: unit test for card section (WEB-21)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#41]
Currently do not have any unit test for the cardSection. Need some unit tests for this section to keep the coverage up while also checking for values to ensure it is the correct info being passed that we are expecting. As things change, we would like to ensure the cards have the right info.

If working on this ticket comment below.

**Comment by joshuaow91** [comment]
working on this

**Comment by TheDThompsonDev** [comment]
Any updates on this?

**Comment by joshuaow91** [comment]
> Any updates on this?

The PR(49) for this was merged to main on Sunday
