### ISSUE TITLE
chore: navbar in mobile view functionality and styling (WEB-22)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#45]
The navbar in mobile view when clicked is moved to the center of the navbar and the buttons are not styled.

When the navbar is clicked, the hamburger menu should move to the center but transform into an X.
All buttons should be the same color as the desktop view.
font-size of 12px
No underlines and the meetup link should be the same size of 12px.

If you have any questions please reach out or check out the figma doc in the readme.

How it should be
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/0725229f-ca3e-43a1-a840-9b11c434e9d6)

Current functionality
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/6da8a67c-15cd-4c72-8535-07a48b3cc558)

**Comment by Anureng** [comment]
I created the PR for this issue , please check

**Comment by TheDThompsonDev** [comment]
As we have not heard back from Anureng, this ticket is still open

**Comment by choir27** [comment]
I'll work on this! ^^

**Comment by ryandotfurrer** [comment]
@choir27 let me know if you want any help with this

**Comment by choir27** [comment]
@ryandotfurrer thanks man, I appreciate it! :D

**Comment by choir27** [comment]
@TheDThompsonDev I noticed in the Figma, the nav bar is aligned more to the left versus the DSD Logo, the X nav menu button, and the mobile nav being evenly aligned.

Figma Example:
![Screenshot 2024-03-21 144001](https://github.com/dallassoftwaredevelopers/DSDsite/assets/66279068/19ffc799-1b3e-4fdb-bd09-2952b7e46eba)

The current website:
![Screenshot 2024-03-21 144032](https://github.com/dallassoftwaredevelopers/DSDsite/assets/66279068/bd44fc14-314f-415b-99eb-4302175bff45)

On mobile, did you want to keep the spacing as it currently is, or did you want to have the spacing be similar to what is currently being shown on Figma?

**Comment by TheDThompsonDev** [comment]
contributors are added automatically once their PR is merged to main. The pipeline has that process automatically built into it.

I will message you on Discord because I do not think I understand what is being asked here specifically.
