### ISSUE TITLE
chore: hide video playing section on mobile view (WEB-23)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#46]
Currently on mobile view this section of the website clashes with the design. it will be great to not display this section at all when in mobile view.

![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/bb9883ff-9dde-463e-8448-2e372c87c089)

**Comment by sprashanthv-dev** [comment]
Working on this!
