### ISSUE TITLE
chore: banner text is not mobile friendly (WEB-24)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#47]
In mobile view the banner is not set for it. It would be ideal to have the text reduced in size to fit better on mobile screens.

Font family should stay the same as well as the weight. The font-size should change to 30px.
Reference the figma doc in the readme if you need it.

How it should look
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/5d3c3b2b-ea01-4ba4-af68-d9deccec70eb)

How it currently looks.
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/9df2ade4-84f0-43a8-94f4-661eb0412504)

**Comment by Brayheart** [comment]
https://github.com/dallassoftwaredevelopers/DSDsite/pull/52

Please see pull request.
