### ISSUE TITLE
chore: hero section look on mobile screens (WEB-25)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#48]
The design on desktop is great but this is not ideal for mobile view. For mobile view we would want The text to be reduced in size and instead of the video playing (This is being hidden with WEB-23) we should have an image. The image is at public\assets\mobileHeroImage.png.

The font should be 34px and everything else remaining the same. Text should remain on the left side while the image is on the right. It should look like this
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/a41d8e7e-8d24-4d16-af2d-276830f5aec5)

Reference the figma doc in the read me if you need it.

**Comment by Brayheart** [comment]
I can take this

**Comment by Brayheart** [comment]
![F065A774-9089-4C8D-9140-E17ED73F5116](https://github.com/dallassoftwaredevelopers/DSDsite/assets/30908449/c8be5405-3e28-4e17-9c37-8a85dd4917d5)

Hey Danny, I've noticed that the mobile view doesn't align with what's discussed in this thread/issue. There seems to be a challenge with fitting all the intended content into the mobile layout. I'm willing to explore and make adjustments to the layout and CSS for a better mobile experience. However, I'm unsure whether I should start making changes directly or wait for your guidance. Should I go ahead and propose mobile-specific edits through a pull request, or would you prefer to discuss this first?

**Comment by TheDThompsonDev** [comment]
@Brayheart Hey! Not sure I understand. this ticket is to change the font and hide the video area on mobile and show a still image instead. Just for reference, I just coded this to show what I am talking about. Not a lot of code to do this.

<img width="1046" alt="image" src="https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/a19daf82-d9a0-4af7-98d1-c288b677a39a">
