### ISSUE TITLE
chore: Add Title and Favicon (WEB-26)

### ISSUE THREAD

**Issue by clintonmyers** [dallassoftwaredevelopers/DSDsite#54]
## Add Title and Favicon

Issue Description:

Currently the app does not appear to have a DSD specific title or Favicon.

Implementation Steps:

1. Change the title in layout.tsx to "Dallas Software Developers".
2. Change the description in layout.tsx to "A community dedicated to empowering local developers" (Or whatever @TheDThompsonDev has in mind).
3. Take a copy of the existing DSD logo (dsd-circle-logo.png) and shrink it down to a 32px x 32px and name it favicon.ico.
4. Google how to add favicons to existing Next projects and follow those steps.

Acceptance Criteria:

When navigating to the app, the users should see the DSD icon and aforementioned title in their browser tab.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by climaxmba** [comment]
Working on this
