### ISSUE TITLE
chore: Add details for first contribution to contribution file (WEB-28)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#58]
Add a very detailed way for someone to make their first open source contribution with steps and screenshots.

This should cover how they fork the repo instead of cloning it, how they should make a PR from their fork into ours, and to ensure their PR has had prettier checked before pushing to ensure it passes the pipeline checks.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by David-Ogden-III** [comment]
I'm going to start on this issue!
