### ISSUE TITLE
chore: add details to contributions file on how someone can update their fork (WEB-31)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#67]
## 
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/01fd21b1-81a5-4709-8be6-1f660721fbae)

We had a ticket previously that was adding instructions on how someone could contribute to the repo for the first time, a step by step guide.

Then we had this great suggestion from @climaxmba! It would be great to have instructions for someone completely new to open source on how they can update their forked repo so that their code is not old or facing extra merge conflicts because new branches have been merged in.

Add this to the contributions.md file with screenshots and step-by-step instructions.

Assume that a beginner will be reading and learning from this.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by climaxmba** [comment]
I can work on this if no one is doing it yet ;)

**Comment by TheDThompsonDev** [comment]
go for it
