### ISSUE TITLE
chore: create the join or discord and other social links section (WEB-34)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#72]
Build out the next section of the page under the cards that will have the image on the left side on top of the rectangle image with the social icons being links that are clickable.
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/b4c3132f-2919-4cf3-9efe-b88cadb07e76)

Use the figma in the readme as the source of truth.

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by TheDThompsonDev** [comment]
I will build this since no one has picked this one up yet so we can continue progressing with the web page.

**Comment by tk1ng** [comment]
Hey @TheDThompsonDev, have you already started work on this? If not, I can work on it this weekend.

**Comment by joeoverflowcode** [comment]
Hey there, my name is Joe, I'm new to the DSD. I'd like to tackle this task if it hasn't been completed yet - any updates? Thanks.

**Comment by tk1ng** [comment]
Hey @joeoverflowcode, I'm wrapping up a PR for this [here](https://github.com/dallassoftwaredevelopers/DSDsite/pull/83)

**Comment by GetBlackBoxSolutions** [comment]
Nice job!
