### ISSUE TITLE
fix: made by the community banner on mobile not full width (WEB-37)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#76]
In mobile view, the banner is not the full width and is off a bit. Should cover the space and be centered.
![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/b4d8e073-875c-4032-a413-a4e98fe4de7e)

**Comment by Soumava-221B** [comment]
Hey @TheDThompsonDev i know how to fix this issue can you assign me this issue?

**Comment by TheDThompsonDev** [comment]
> Hey @TheDThompsonDev i know how to fix this issue can you assign me this issue?

Go for it
