### ISSUE TITLE
chore: fix unit tests for navbar to get code coverage back to 100% (WEB-38)

### ISSUE THREAD

**Issue by TheDThompsonDev** [dallassoftwaredevelopers/DSDsite#77]
After running the latest code coverage report our navbar test coverage has dropped when it shouldn't be.

Need some unit tests here to cover it. I know code coverage will eventually drop but this early with as few components as we currently have, this shouldn't be the time for us to drop it.

![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/39189903/fa8d1c7f-d291-4b21-a510-ea7a4548bfde)

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by SamuelHe2024** [comment]
I'll take this one
