### ISSUE TITLE
chore: adjust CSS for BentoSection Component to readjust for mobile view (WEB-39)

### ISSUE THREAD

**Issue by GetBlackBoxSolutions** [dallassoftwaredevelopers/DSDsite#85]
## Task

Update the BentoSection component to follow the design of the Figma for mobile view. 

![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/110210295/7949d4e7-e94d-44ec-bd50-94894cf8f6be)

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by aayardev** [comment]
I want to work on this issue but where I can find the figma design link ?

**Comment by smclairecarden** [comment]
> I want to work on this issue but where I can find the figma design link ?

It's in the ReadMe, also here - https://www.figma.com/file/8cpiqfhzCrzjqK7UOyJKvn/DSD?type=design&node-id=0-1&mode=design.

**Comment by GetBlackBoxSolutions** [comment]
@aayardev have you started on this?

**Comment by aayardev** [comment]
> @aayardev have you started on this?

yes

**Comment by GetBlackBoxSolutions** [comment]
FYI: You have two weeks from today to finish otherwise we will reassign to make sure task do not get stale. We look forward to your contributions. Thank you.

**Comment by GetBlackBoxSolutions** [comment]
This task is available
