### ISSUE TITLE
chore: create a new page directory for speakers (WEB-41)

### ISSUE THREAD

**Issue by GetBlackBoxSolutions** [dallassoftwaredevelopers/DSDsite#87]
## Task

This task is to take advantage of NEXT.JS app app routing structure by creating a new page named "speakers" that will give us a new route. For now just worry about completing the steps below. 

1. Create a new directory under the src directory that will be called "pages". 
2. Under the new pages directory create a new directory called "speakers" and a file under that directory called "index.tsx". 
3. Inside the index create a new component with the name "Speakers" and give it a H1 heading of "Past Speakers".
4. Create a file called pastSpeakers.module.css to hold the styles of the new page and style the H1 on this page with color #3c3db9. 

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by Soumava-221B** [comment]
i am working on this issue
