### ISSUE TITLE
chore: create a footer according to the Figma design (WEB-42)

### ISSUE THREAD

**Issue by GetBlackBoxSolutions** [dallassoftwaredevelopers/DSDsite#90]
## Task

* Create a footer component according to the Figma designs and incorporate into the Layout component.  
* Create a unit test for the new footer component. 

*Note: For now the links in the right side can just point to home. 

https://www.figma.com/design/8cpiqfhzCrzjqK7UOyJKvn/DSD?node-id=0%3A1&t=xOv8WxDjy2eu1wqy-1

![image](https://github.com/dallassoftwaredevelopers/DSDsite/assets/110210295/538ac0ec-5ec3-4b16-a1fc-b1094546ddd3)

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by Nur4ck** [comment]
Hi I would like to contribute to this ticket. Should the file of the new component be placed inside the app/components directory or inside a subdirectory of the components/layout directory ?
